version: "3.3"
services:
  spark-master:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
  spark-worker-b:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data
  
  postgres:
      hostname: postgres
      container_name: postgres
      image: 'postgres:14-bullseye'
      environment:
          POSTGRES_USER: 'test'
          POSTGRES_PASSWORD: 'test'
          POSTGRES_DB: 'test'
          PGDATA: /data/postgres
      volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - postgres:/data/postgres
      ports:
          - "5432:5432"
  minio:
    user: root
    hostname: minio
    image: 'minio/minio:RELEASE.2021-01-08T21-18-21Z'
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
  
  # metabase:
  #   image: metabase/metabase:latest
  #   restart: always
  #   environment:
  #     MB_DB_TYPE: "postgres"
  #     MB_DB_DBNAME: "test"
  #     MB_DB_PORT: "5432"
  #     MB_DB_USER: "test"
  #     MB_DB_PASS: "test"
  #     MB_DB_HOST: "postgres"
  #   ports:
  #     - '3001:3000'
  #   depends_on:
  #     - postgres


volumes:
  postgres:
  minio-data:
    driver: local
